[project]
name = "twitchcon-attendees"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pillow>=11.2.1",
    "requests>=2.32.3",
    "typst>=0.13.2",
]

[tool.ruff]
indent-width = 2